### ISSUE TITLE
Energy saving mode

### ISSUE THREAD

**Issue by markste-in** [OpenAcousticDevices/AudioMoth-Configuration-App#10]
When I hover over "Enable energy saving mode" I get the comment "enables energy saving mode".

I think it would be helpful to change the comment to what it actually does.
From your twitter comments my understanding is that the internal sampling rate is reduced to 192 kHz?

I guess in this case it wouldn't make sense to record with more than 96 kHz even though I am still able to configure sampling rates up to 384 kHz? Maybe a warning should pop up that the effective audio rate is reduced to 96 kHz?

Or did I get this feature wrong? :D

**Comment by AlexRogersCS** [comment]
Yes, it's quite tricky to get all the details into the very short pop-up so the manual is the better reference. The sample rate of the recording that you make is unchanged. You can set any sample rate. However, there won't be any energy saving for sample rates below 48kHz.
