### ISSUE TITLE
EFM Drivers

### ISSUE THREAD

**Issue by neilh10** [OpenAcousticDevices/AudioMoth-Configuration-App#11]
Hi I got my HdyroMoth and it said it was the same as the AudioMoth.
When I follow instructions, put in batteries, uSD, download this App and plugin the board microUSB device, green LED comes on, my Windows 11 dings to say it has detected the board, 
However the App doesn't detect the board.

When I list from windows Power Shell the usb devices (thanks to https://tuntoon.com/how-to-see-connected-usb-devices/) 
$ Get-PnpDevice -PresentOnly | Where-Object { $_.InstanceId -match 'USB' }
and I see a new device
```
Status     Class           FriendlyName                 InstanceId     
Error      USB             EasyLog USB Device        USB\VID_10C4...
```

Now I do have an older temperature logger  called "EasyLog"  https://www.lascarelectronics.com/software/easylog-software/easylog-usb

I expect it to work, but if not for enough detail that I can self help.
Since detecting and connecting over USB with the XxxMoth is a basic physical requirement, it would be nice if the AudioMoth-Configuration-App indicate that it has connected. A nice feature of the Hobo Configuration App  - though it connects on COMx (visual snippet below with yellow highlighting on status) 
From https://www.onsetcomp.com/hoboware-free-download

![image](https://user-images.githubusercontent.com/2766619/187040389-da38f2a7-73d6-43d6-8e40-f22b55fd34ae.png)

Similarly the WinSitu App from In-situ https://in-situ.com/us/win-situ-software has a connected device ICON bottom right
![image](https://user-images.githubusercontent.com/2766619/187040733-96a805d1-6706-4ab7-8d6a-04b9d38286b0.png)

The AudioMoth-Configuration-App does grey out the Device Id and Firmware Version - which is the only clue that I got that something maybe is missing.

I would hope that the AudioMoth-Configuration-App would check the right drivers are installed, and let me know the status if it can't find them, and perhaps a link on what to do.  App help is not very useful.

Help - Open Acoustic Devices Website - takes me to the marketing page. 

The physical marking of the device I used is 
HydroMoth 1.0.0 with a printed bar code  VSC 10364743 LFNC

I tried registering and searching https://www.openacousticdevices.info/support/ but  no information.
I've looked for circuit diagram to understand what USB interface/circuit is https://github.com/OpenAcousticDevices/Datasheets/blob/main/AudioMoth_Dev_Datasheet/AudioMoth_Dev_Datasheet.pdf
but seems that is a closely held secret.  
Overall impressions looks a great device, just I can't get it configured.

**Comment by neilh10** [comment]
In case I should be doing anything else I've posted about this at https://www.openacousticdevices.info/support/configuration-support/app-not-connecting-with-hydromoth

**Comment by AlexRogersCS** [comment]
Hi, The time on the AudioMoth Configuration App will go black and start counting as soon as the app connects to the AudioMoth. The Configuration App uses the system drivers. However, unfortunately, the problem is the EasyLog driver which incorrectly attaches itself to the Silicon Labs PID and VID pair. Deleting this driver and restoring the original system HID driver will allow it to work properly. Alex
