### ISSUE TITLE
Timestamp for expanded T-Wave files

### ISSUE THREAD

**Issue by VDierks** [OpenAcousticDevices/AudioMoth-Configuration-App#12]
Hi, 
for easier processing of the files I split the T-Wave files into 10s-parts using the AudioMoth-Configuration-App. After splitting the files, each wave-file has the timestamp set to the time when the split process startet, while the filename contains the actual recording time and date.

I'd like to have an option whitin the app that sets the timestamp of the wave-file to match the recording time.

Kind Regards
Volker Dierks

**Comment by AlexRogersCS** [comment]
We'll look into adding that as an option.
