### ISSUE TITLE
Not supporting "-" character in WAV file prefix

### ISSUE THREAD

**Issue by YvesBas** [OpenAcousticDevices/AudioMoth-Configuration-App#7]
The "Add WAV file prefix" function does not support the "-" character which is unfortunately present in site naming in the French Bat Monitoring Programme (Vigie-Chiro). Is it something you could fix easily? Thanks in advance!

**Comment by AlexRogersCS** [comment]
Yep, we'll look at that.

**Comment by YvesBas** [comment]
Thanks!

**Comment by pcprince** [comment]
Hyphens can be used as part of the prefix. The change was made ages ago but I forgot to close this issue.
Thanks for the suggestion!
