### ISSUE TITLE
Option to remove T at the end of wave files after expanding them?

### ISSUE THREAD

**Issue by YvesBas** [OpenAcousticDevices/AudioMoth-Configuration-App#8]
Dear developers, would it be possible to add an option where splitted and expanded WAV files would not have the "T" character at the end? It would make the names of WAV files fit the standard we are using since 2014 in our monitoring programme. We started with WA recorders like many other programmes and yours is exactly the same except for this "T" at the end...

**Comment by AlexRogersCS** [comment]
The expanded files won't have the 'T' character at the end. Only the raw files from the AudioMoth. After expansion, they become regular WAV files with not 'T' character in the filename.

**Comment by YvesBas** [comment]
you're absolutely right, sorry for this mistake...
