### ISSUE TITLE
Slow expanding and splitting

### ISSUE THREAD

**Issue by YvesBas** [OpenAcousticDevices/AudioMoth-Configuration-App#9]
Dear developers, I noticed that your "Expand Audiomoth T.WAV Recordings" was much slower than Kaleidoscope. It may be because this task is not parallelised yet? Would it be something you would consider to improve in the future? For now, this prevents massive use of the Audiomoth in our Vigie-Chiro monitoring programme (~500 participants). Users with more than 3 Audiomoth cannot process recordings of 1 night during the following day.... 
Thanks for your response!

**Comment by YvesBas** [comment]
Hi! It seems in fact that it is really quick under Linux, but really slow under Windows... Maybe it gives you some idea about this issue? That would be great, we can't really ask our users to go on Linux....

**Comment by AlexRogersCS** [comment]
Hi, Is this still an issue for you. We released an update to 1.5.1 which addressed a speed issue with large files. Can you describe how long it is taking on Windows (e.g. file size and number of files).

**Comment by YvesBas** [comment]
ok, sorry I just tested it and it is fine now! Thanks a lot!!
